apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
   # these lables are relica set lables
  labels:
    app: frontend
    tier: web
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    # relicaset use these lables to find the pods for creating desired number of replacs
    matchLabels:
      app: frontend
      tier: web
  # pod template    
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
